# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
wally = "UpliftGames/wally@0.3.2"
rojo ="rojo-rbx/rojo@7.4.0-rc2"
selene = "Kampfkarren/selene@0.25.0"
stylua = "JohnnyMorganz/StyLua@0.17.1"
remodel = "rojo-rbx/remodel@0.11.0"