[package]
name = "mellysoft/mds"
version = "2.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "lucasmzreal/fastsignal@10.2.1"
Promise = "evaera/promise@^4"
TableUtil = "sleitnick/table-util@^1"